import localFont from "@next/font/local";
import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iranSans = localFont({
  src: "../public/fonts/IRAN.woff2",
  variable: "--font-iranSans",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${iranSans.className}`} dir="rtl">
        <Header />
        {children}
      </body>
    </html>
  );
}
